# fly.toml file generated for charlendar on 2023-03-04T11:18:03+09:00
# to run without pm2 : experimental > cmd = "npm run dev"
# to run with pm2 : experimental > cmd = "pm2 start pm2.config.js --env development"

app = "charlendar"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"
  [build.args]
    NODE_VERSION = "16"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[experimental]
  auto_rollback = true
  cmd = "npm run dev"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443


  [[services.tcp_checks]]
    grace_period = "2s"
    interval = "5s"
    timeout = "2s"
